/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '../custom';

import { PageBackground as PageBackground } from './components/page-background/page-background';

interface HTMLPageBackgroundElement extends PageBackground, HTMLElement {
}
declare var HTMLPageBackgroundElement: {
  prototype: HTMLPageBackgroundElement;
  new (): HTMLPageBackgroundElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "page-background": HTMLPageBackgroundElement;
  }
  interface ElementTagNameMap {
      "page-background": HTMLPageBackgroundElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "page-background": JSXElements.PageBackgroundAttributes;
      }
  }
  namespace JSXElements {
      export interface PageBackgroundAttributes extends HTMLAttributes {
        
          type?: any,
          value?: any,
          key?: any,
          gradient?: any
      }
  }
}

import { PageLayout as PageLayout } from './components/page-layout/page-layout';

interface HTMLPageLayoutElement extends PageLayout, HTMLElement {
}
declare var HTMLPageLayoutElement: {
  prototype: HTMLPageLayoutElement;
  new (): HTMLPageLayoutElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "page-layout": HTMLPageLayoutElement;
  }
  interface ElementTagNameMap {
      "page-layout": HTMLPageLayoutElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "page-layout": JSXElements.PageLayoutAttributes;
      }
  }
  namespace JSXElements {
      export interface PageLayoutAttributes extends HTMLAttributes {
        
          direction?: any,
          width?: any
      }
  }
}

